name: xray_sis_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  image_picker: ^1.0.4
  image: ^4.0.0
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  camera_web: ^0.3.5
  camera: ^0.11.0
  universal_html: ^2.0.6
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true